### ISSUE TITLE
Error occured while make (macOS 10.13.6)

### ISSUE THREAD

**Issue by yosiot** [denji/cpulimit#5]
Followed in the description in README.md, I run the command
$  make

But I met error message
  /bin/sh: n: command not found
  make[1]: [cpulimit.1] Error 127 (ignored)

The executable module named "cpulimit" is created in "src" directory,
but its man source file "cpulimit.1" is empty (0 byte).

My environment : Xcode 10.1 under macOS 10.13.6 (High Sierra)

The following is the summary of command sequence what I did.

$ git clone https://github.com/denji/cpulimit
$ cd cpulimit
$ git checkout -b build
$ ls -a
.   .astylerc  .git       .travis.yml  Makefile   src
..  .format.sh .gitignore LICENSE      README.md  test
$ make
cd src && /Applications/Xcode.app/Contents/Developer/usr/bin/make all
cc -c list.c -Os -Wall -g -D_GNU_SOURCE
cc -c process_iterator.c -Os -Wall -g -D_GNU_SOURCE
cc -c process_group.c -Os -Wall -g -D_GNU_SOURCE
cc -o cpulimit cpulimit.c list.o process_iterator.o process_group.o -Os -Wall -g -D_GNU_SOURCE
n "CPU Utilization Limiter" -s 1 -s https://github.com/denji/cpulimit -N ./cpulimit > cpulimit.1
/bin/sh: n: command not found
make[1]: [cpulimit.1] Error 127 (ignored)

   (snip)

**Comment by denji** [comment]
https://github.com/denji/cpulimit/blob/master/src/Makefile#L43-L44
HELP2MAN   := $(shell which help2man)

help2man installed?

**Comment by denji** [comment]
brew install help2man
